//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 02:01:14 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wfmc.org/2009/XPDL2.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.wfmc._2009.xpdl2;
